# Use the Ubuntu image
from ubuntu:latest

# Update and install required packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

# Set The Working directory
WORKDIR /app

# Install JupyterLab
RUN pip3 install jupyterlab

# EXPOSE port 8080
EXPOSE: 8080

# Start JupyterLab on port 8080 without authentication
CND ["jupyter", "lab", "--ip=0.0.0.0", "--port=8080", "--no-browser", "--allow-root", "NotebookApp.token=''"]
